Cleanup boilerplate code
code4sac/trash-ai pull request #3
Opened 2021-10-27 14:21 UTC by josephmfaulkner

One Application, ready for action

2021-11-04 02:54 UTC, josephmfaulkner commented
@feydan : There we go, one shiny pull request ready for review.

2021-11-04 12:46 UTC, goonchersen commented on backend-nodejs/.gitignore
> +node_modules
I typically like to include a trailing slash on directories whose contents I want ignored.  It's just a visual cue for me to understand "node_modules is a _directory_, and this won't apply to files named "node_modules"

2021-11-04 12:50 UTC, goonchersen commented on backend-nodejs/.sequelizerc
> +const path = require('path');
It's probably helpful to eliminate all things _sequelize_ from the pull request.  I doubt that the Trash API app will require any persistence (beyond committing images to an S3 bucket).  All of the _sequelize_ artifacts will just continue to clutter things up.

2021-11-04 12:52 UTC, goonchersen commented on backend-nodejs/README.md
> +This repository goes with [webapp-boilerplate-frontend](https://github.com/josephmfaulkner/webapp-boilerplate-frontend)
You'll likely want to eliminate all references to your own GitHub account and repositories

2021-11-04 12:52 UTC, goonchersen commented on backend-nodejs/README.md
> +## Local DB Development
Remove

2021-11-04 12:52 UTC, goonchersen commented on backend-nodejs/README.md
> +**Add DB to PG Admin:** Servers > Create > Server
Ibid.

2021-11-04 12:54 UTC, goonchersen commented on backend-nodejs/docker-compose.yml
> +version: "3.9"
Again, persistence probably isn't necessary, so I wouldn't bother having the PostgreSQL database spun up here

2021-11-07 13:49 UTC, goonchersen requested changes
I began working through this PR file-by-file, but then decided that a single comment associated with the review is probably all that's necessary.  Suggestions are as follows:

- Eliminate persistence capabilities and artifacts.  At this point, with no applicable user story, persistence isn't necessary, and only clutters the code.  One of the tenets of lean software development is to implement only what is necessary, and I think that that tenet is applicable here.

- The use of _passport.js_ is great, but I'm not certain that authentication is a valid user story.  We don't have the sort of application that requires authentication -- _yet_, at least -- so I'd take it out.  I _can_ imagine the need for authorization using OAuth and a valid JWT token in request headers, but on the surface that's sufficient to POST images to any data set.  Again, thinking lean, I'd remove the authentication work.

- I believe that the only known use case for the backend up to this point is a simple endpoint protected by a valid JWT token where a user can upload a photograph, leverage the image recognition model in association with an object detection filter, and return the annotated photograph to the user by way of an HTTP response.  The team collectively has questions to Win pending, and I believe it would be helpful to wait until we have greater certainty and not risk implementing what won't be necessary.

- Keep the _express.js_ server configuration there.  I see a need for just a single endpoint that returns a 200, with the possibility of protecting the endpoint by means of the JWT token.

2021-12-16 04:27 UTC, merged