Changes below
code4sac/trash-ai pull request #63
Opened 2022-08-08 07:06 UTC by shollingsworth

* adjusted dialog for lower parts of the image
* updated for mobile
* Added display div, added scores, adjusted the way labels are applied.
* Classification widgets

2022-08-20 22:35 UTC, feydan requested changes
One small comment -- looked like there is a duplicate prototype function declaration in util.ts

2022-08-20 22:35 UTC, feydan commented on frontend/src/lib/util.ts
> +Timer.prototype.setTimeout = function (callback: Function, time: number) {
This looks like a duplicate (declared above as well)

2022-11-03 16:35 UTC, shollingsworth commented
@feydan changes are made, also removed a duplicate about.vue file.

2022-11-03 20:19 UTC, feydan approved these changes
looks good!

2022-11-03 22:26 UTC, merged